<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Shared\BlueLagoon.Shared.Abstractions\BlueLagoon.Shared.Abstractions.csproj" />
    <ProjectReference Include="..\BlueLagoon.Modules.Notifications.Core\BlueLagoon.Modules.Notifications.Core.csproj" />
  </ItemGroup>

</Project>
