version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: blue-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: blue_lagoon
      POSTGRES_USER: blue_owner
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      IAM_PASSWORD: ${IAM_PASSWORD}
      CATALOG_PRICING_PASSWORD: ${CATALOG_PRICING_PASSWORD}
      BILLING_PAYMENT_PASSWORD: ${BILLING_PAYMENT_PASSWORD}
      CRM_PASSWORD: ${CRM_PASSWORD}
      CUSTOMER_OPERATION_PASSWORD: ${CUSTOMER_OPERATION_PASSWORD}
      DEADLINE_MANAGEMENT_PASSWORD: ${DEADLINE_MANAGEMENT_PASSWORD}
      EMPLOYEE_INCETIVE_PASSWORD: ${EMPLOYEE_INCETIVE_PASSWORD}
      INFRASTRUCTURE_MANAGEMENT_PASSWORD: ${INFRASTRUCTURE_MANAGEMENT_PASSWORD}
      NOTIFICATION_PASSWORD: ${NOTIFICATION_PASSWORD}
      RETENTION_TERMINATION_PASSWORD: ${RETENTION_TERMINATION_PASSWORD}
      SALE_CONTRACTING_PASSWORD: ${SALE_CONTRACTING_PASSWORD}
      TECHNICAL_SUPPORT_PASSWORD: ${TECHNICAL_SUPPORT_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - blue_postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  blue_postgres_data:
