version: "3.9"

services:
  postgres:
    image: postgres:18
    container_name: blue-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: blue_lagoon
      POSTGRES_USER: blue_owner
      POSTGRES_PASSWORD: HasloJestMiekkieJakMaslo0

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
