// <auto-generated />
using System;
using System.Collections.Generic;
using BlueLagoon.Modules.Iam.Core.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlueLagoon.Modules.Iam.Core.Migrations
{
    [DbContext(typeof(IamDbContext))]
    [Migration("20260118011654_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("iam")
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApplicationType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("application_type");

                    b.Property<string>("ClientId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("client_secret");

                    b.Property<string>("ClientType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_type");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<string>("ConsentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("consent_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("JsonWebKeySet")
                        .HasColumnType("text")
                        .HasColumnName("json_web_key_set");

                    b.Property<Guid?>("ModificatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificator_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("modified_at");

                    b.Property<string>("Permissions")
                        .HasColumnType("text")
                        .HasColumnName("permissions");

                    b.Property<string>("PostLogoutRedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("post_logout_redirect_uris");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("RedirectUris")
                        .HasColumnType("text")
                        .HasColumnName("redirect_uris");

                    b.Property<string>("Requirements")
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<string>("Settings")
                        .HasColumnType("text")
                        .HasColumnName("settings");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModificatorId");

                    b.ToTable("application", "iam");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.Authorization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ModificatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificator_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("modified_at");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Scopes")
                        .HasColumnType("text")
                        .HasColumnName("scopes");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModificatorId");

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("authorization", "iam");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUrl")
                        .HasColumnType("text")
                        .HasColumnName("base_url");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Descriptions")
                        .HasColumnType("text")
                        .HasColumnName("descriptions");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("DisplayNames")
                        .HasColumnType("text")
                        .HasColumnName("display_names");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ModificatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificator_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OpenApiPath")
                        .HasColumnType("text")
                        .HasColumnName("open_api_path");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<string>("Resources")
                        .HasColumnType("text")
                        .HasColumnName("resources");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModificatorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("module", "iam");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.RegisteredEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("http_method");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ModificatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificator_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("modified_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ModuleName", "BlueLagoon.Modules.Iam.Core.DAL.Entities.RegisteredEndpoint.ModuleName#ModuleName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("module_name");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OperationDescription", "BlueLagoon.Modules.Iam.Core.DAL.Entities.RegisteredEndpoint.OperationDescription#OperationDescription", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("operation_description");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OperationId", "BlueLagoon.Modules.Iam.Core.DAL.Entities.RegisteredEndpoint.OperationId#OperationId", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("operation_id");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "OperationSummary", "BlueLagoon.Modules.Iam.Core.DAL.Entities.RegisteredEndpoint.OperationSummary#OperationSummary", b1 =>
                        {
                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("operation_summary");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Path", "BlueLagoon.Modules.Iam.Core.DAL.Entities.RegisteredEndpoint.Path#Path", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("path");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModificatorId");

                    b.ToTable("registered_endpoint", "iam");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ModificatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificator_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("modified_at");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModificatorId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("role", "iam");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.RoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ModificatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificator_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModificatorId");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claim", "iam");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid?>("AuthorizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("authorization_id");

                    b.Property<string>("ConcurrencyToken")
                        .IsConcurrencyToken()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("concurrency_token");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiration_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ModificatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificator_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("modified_at");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Properties")
                        .HasColumnType("text")
                        .HasColumnName("properties");

                    b.Property<DateTime?>("RedemptionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("redemption_date");

                    b.Property<string>("ReferenceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_id");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("subject");

                    b.Property<string>("Type")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("type");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AuthorizationId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModificatorId");

                    b.HasIndex("ReferenceId")
                        .IsUnique();

                    b.HasIndex("ApplicationId", "Status", "Subject", "Type");

                    b.ToTable("token", "iam");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<Guid?>("ModificatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificator_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("modified_at");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FirstName", "BlueLagoon.Modules.Iam.Core.DAL.Entities.User.FirstName#UserFirstName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("first_name");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "LastName", "BlueLagoon.Modules.Iam.Core.DAL.Entities.User.LastName#UserLastName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("last_name");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModificatorId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("user", "iam");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.UserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ModificatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificator_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("modified_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModificatorId");

                    b.HasIndex("UserId");

                    b.ToTable("user_claim", "iam");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.UserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ModificatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificator_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("modified_at");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModificatorId");

                    b.HasIndex("UserId");

                    b.ToTable("user_login", "iam");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ModificatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificator_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("modified_at");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModificatorId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_role", "iam");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.UserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("creator_id");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<Guid?>("ModificatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("modificator_id");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp(0)")
                        .HasColumnName("modified_at");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.HasIndex("CreatorId");

                    b.HasIndex("ModificatorId");

                    b.ToTable("user_token", "iam");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.Application", b =>
                {
                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Creator")
                        .WithMany("ApplicationCreators")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Modificator")
                        .WithMany("ApplicationModificators")
                        .HasForeignKey("ModificatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Modificator");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.Authorization", b =>
                {
                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.Application", "Application")
                        .WithMany("Authorizations")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Creator")
                        .WithMany("AuthorizationCreators")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Modificator")
                        .WithMany("AuthorizationModificators")
                        .HasForeignKey("ModificatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Creator");

                    b.Navigation("Modificator");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.Module", b =>
                {
                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Creator")
                        .WithMany("ModuleCreators")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Modificator")
                        .WithMany("ModuleModificators")
                        .HasForeignKey("ModificatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Modificator");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.RegisteredEndpoint", b =>
                {
                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Creator")
                        .WithMany("RegisteredEndpointCreators")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Modificator")
                        .WithMany("RegisteredEndpointModificators")
                        .HasForeignKey("ModificatorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("Modificator");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.Role", b =>
                {
                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Creator")
                        .WithMany("RoleCreators")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Modificator")
                        .WithMany("RoleModificators")
                        .HasForeignKey("ModificatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Modificator");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.RoleClaim", b =>
                {
                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Creator")
                        .WithMany("RoleClaimCreators")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Modificator")
                        .WithMany("RoleClaimModificators")
                        .HasForeignKey("ModificatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Modificator");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.Token", b =>
                {
                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.Application", "Application")
                        .WithMany("Tokens")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.Authorization", "Authorization")
                        .WithMany("Tokens")
                        .HasForeignKey("AuthorizationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Creator")
                        .WithMany("TokenCreators")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Modificator")
                        .WithMany("TokenModificators")
                        .HasForeignKey("ModificatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Authorization");

                    b.Navigation("Creator");

                    b.Navigation("Modificator");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", b =>
                {
                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Creator")
                        .WithMany("UserCreators")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Modificator")
                        .WithMany("UserModificators")
                        .HasForeignKey("ModificatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Modificator");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.UserClaim", b =>
                {
                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Creator")
                        .WithMany("UserClaimCreators")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Modificator")
                        .WithMany("UserClaimModificators")
                        .HasForeignKey("ModificatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Modificator");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.UserLogin", b =>
                {
                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Creator")
                        .WithMany("UserLoginCreators")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Modificator")
                        .WithMany("UserLoginModificators")
                        .HasForeignKey("ModificatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Modificator");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.UserRole", b =>
                {
                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Creator")
                        .WithMany("UserRoleCreators")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Modificator")
                        .WithMany("UserRoleModificators")
                        .HasForeignKey("ModificatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Modificator");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.UserToken", b =>
                {
                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Creator")
                        .WithMany("UserTokenCreators")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", "Modificator")
                        .WithMany("UserTokenModificators")
                        .HasForeignKey("ModificatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Modificator");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.Application", b =>
                {
                    b.Navigation("Authorizations");

                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.Authorization", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("BlueLagoon.Modules.Iam.Core.DAL.Entities.User", b =>
                {
                    b.Navigation("ApplicationCreators");

                    b.Navigation("ApplicationModificators");

                    b.Navigation("AuthorizationCreators");

                    b.Navigation("AuthorizationModificators");

                    b.Navigation("ModuleCreators");

                    b.Navigation("ModuleModificators");

                    b.Navigation("RegisteredEndpointCreators");

                    b.Navigation("RegisteredEndpointModificators");

                    b.Navigation("RoleClaimCreators");

                    b.Navigation("RoleClaimModificators");

                    b.Navigation("RoleCreators");

                    b.Navigation("RoleModificators");

                    b.Navigation("TokenCreators");

                    b.Navigation("TokenModificators");

                    b.Navigation("UserClaimCreators");

                    b.Navigation("UserClaimModificators");

                    b.Navigation("UserCreators");

                    b.Navigation("UserLoginCreators");

                    b.Navigation("UserLoginModificators");

                    b.Navigation("UserModificators");

                    b.Navigation("UserRoleCreators");

                    b.Navigation("UserRoleModificators");

                    b.Navigation("UserTokenCreators");

                    b.Navigation("UserTokenModificators");
                });
#pragma warning restore 612, 618
        }
    }
}
