CREATE SCHEMA iam;

CREATE ROLE iam_user LOGIN PASSWORD 'HannahMontana@1@';

GRANT USAGE ON SCHEMA iam TO iam_user;
GRANT CREATE ON SCHEMA iam TO iam_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA iam
GRANT ALL ON TABLES TO iam_user;