<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Components\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Components\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <None Update="module.iam.development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
      <None Update="module.iam.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BlueLagoon.Modules.Iam.Core\BlueLagoon.Modules.Iam.Core.csproj" />
  </ItemGroup>

</Project>
